// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyHotel.Models
{
    public partial class BankAccount
    {
        public int Id { get; set; }
        public int? Customerid { get; set; }
        public decimal? Balance { get; set; }

        public virtual Customer Customer { get; set; }
    }
}