// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyHotel.Models
{
    public partial class Customer
    {
        public Customer()
        {
            BankAccounts = new HashSet<BankAccount>();
            Payments = new HashSet<Payment>();
            Roombookings = new HashSet<Roombooking>();
        }

        public int Customerid { get; set; }
        public string Customername { get; set; }
        public bool? Gender { get; set; }
        public string Address { get; set; }
        public string Phonenumber { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }

        public virtual ICollection<BankAccount> BankAccounts { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
        public virtual ICollection<Roombooking> Roombookings { get; set; }
    }
}