// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyHotel.Models
{
    public partial class Payment
    {
        public int Paymentid { get; set; }
        public int? Bookingid { get; set; }
        public int? Customerid { get; set; }
        public decimal? Paymentamt { get; set; }

        public virtual Roombooking Booking { get; set; }
        public virtual Customer Customer { get; set; }
    }
}