// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyHotel.Models
{
    public partial class Roombooking
    {
        public Roombooking()
        {
            Payments = new HashSet<Payment>();
        }

        public int Bookingid { get; set; }
        public int? Customerid { get; set; }
        public int? Roomid { get; set; }
        public DateTime? Bookingfrom { get; set; }
        public DateTime? BookingTo { get; set; }

        public virtual Customer Customer { get; set; }
        public virtual Room Room { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
    }
}