// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace MyHotel.Models
{
    public partial class Room
    {
        public Room()
        {
            Roombookings = new HashSet<Roombooking>();
        }

        public int Roomid { get; set; }
        public string Roomimage { get; set; }
        [NotMapped]
        public IFormFile roomimage { get; set; }
        public int? Roomprice { get; set; }
        public string Roomtype { get; set; }
        public int? Roomcapacity { get; set; }
        public bool? Available { get; set; }

        public virtual ICollection<Roombooking> Roombookings { get; set; }
    }
}